### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by antonf-ekb** [MineralsCloud/pgm#19]
Dear pgm developers!
I really appreciate idea of the code, however, I've got some issues and questions.
1) As can we see from the input files in the examples folder, there is `S_el = ... `variable, which is not written by the conventional qha input maker. Should I add  S_el = 0 by hands? Because now pgm drops an error, which I guess is due to the absence of S_el.
2) In the example .yaml file there is `ratio : 1.2` parameter, which is not described in the manual. Could you comment on its meaning?
3) I am wondering that in the casio3 example pressure range starts just from 0, while in conventional QHA calculations  to find the equilibrium volume at P=0 we include some points corresponding to negative pressures... Doesn't pgm require this?

**Comment by antonf-ekb** [comment]
Hi,
Thank you for the answer! May be in the future releases you could add that if there is no "S_el", by default it is set to zero since, I think, it is not very convinient to add S_el = 0 by hand for many lines in several input files. Regarding the volume expansion ratio - could you tell some approximate range for it?
Best regards,
Anton.

**Comment by underhill1886** [comment]
Hi Anton,
Thank you for your suggestion. This is good advice. We could also make scripts that easily convert the qha input into pgm input.
Regarding the volume expansion ratio, I would say 1.05 - 1.2 is a good range. Bigger than that would result in too much extrapolation.
Best regards,
Hongjin
